### ISSUE TITLE
howler.js sprite demo not working

### ISSUE THREAD

**Issue by PluginIO** [Retyped/Demos#1]
howler.js sprite demo does not seem to be working.

OS: MacOS Mojave.
Browser: Chrome Version 74.0.3729.108 (Official Build) (64-bit)

<img width="1414" alt="Screenshot 2019-04-27 at 01 10 03" src="https://user-images.githubusercontent.com/1716106/56841994-3cb7d680-6889-11e9-9c92-c9f6858aa16a.png">

**Comment by AndreyChechel** [comment]
Thanks for noticing that. Fixed.
